# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env: 
  NAMESPACE: Discord.Net.Extensions.Interactions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Auth
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Misha-133/index.json"
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Publish package
      run: dotnet nuget push "$NAMESPACE/bin/Release/$NAMESPACE.1.1.0.nupkg" --source "github" --api-key ACCESS_TOKEN
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
